"""add trouble fields

Revision ID: cacadad236f6
Revises: d33639489416
Create Date: 2026-09-12 14:23:54.908907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cacadad236f6'
down_revision: Union[str, Sequence[str], None] = 'd33639489416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('trouble_type', sa.String(length=50), nullable=False))
    op.add_column('samples', sa.Column('trouble_detail', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'trouble_detail')
    op.drop_column('samples', 'trouble_type')
    # ### end Alembic commands ###
