"""add date and place

Revision ID: d33639489416
Revises: b252355876d4
Create Date: 2026-09-09 13:11:06.034863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33639489416'
down_revision: Union[str, Sequence[str], None] = 'b252355876d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('samples', sa.Column('place', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'place')
    op.drop_column('samples', 'date')
    # ### end Alembic commands ###
