/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Samples
         * @description サンプル一覧を取得する。q があるときは名前・場所をキーワード検索する。
         */
        get: operations["get_samples_samples_get"];
        put?: never;
        /**
         * Create Sample
         * @description サンプルを追加する
         */
        post: operations["create_sample_samples_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/samples/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        // ===== 追加: PUT 更新 =====
        /**
         * Update Sample
         * @description サンプルを全項目で上書き更新する（PUT）
         */
        put: operations["update_sample_samples__sample_id__put"];
        // ===== 追加ここまで =====
        post?: never;
        /**
         * Delete Sample
         * @description サンプルを削除する
         */
        delete: operations["delete_sample_samples__sample_id__delete"];
        options?: never;
        head?: never;
        // ===== 追加: PATCH 部分更新 =====
        /**
         * Partial Update Sample
         * @description サンプルの一部フィールドだけ更新する（PATCH）
         */
        patch: operations["partial_update_sample_samples__sample_id__patch"];
        // ===== 追加ここまで =====
        trace?: never;
    };
    "/samples/{sample_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sample_messages"];
        put?: never;
        post: operations["create_sample_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SampleCreate */
        SampleCreate: {
            /** Name */
            name: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Place */
            place: string;
            trouble_type: string;
            trouble_detail?: string;
            /** Email */
            email: string;
            expected_actions?: string | null;
            actual_actions?: string | null;
            error_code?: string | null;
            ai_initial_response?: string | null;
        };
        // ===== 追加: 更新用スキーマ =====
        /** SampleUpdate */
        SampleUpdate: {
            /** Name */
            name: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Place */
            place: string;
            trouble_type: string;
            trouble_detail: string;
            /** Email（照合用） */
            email: string;
            expected_actions?: string | null;
            actual_actions?: string | null;
            error_code?: string | null;
            ai_initial_response?: string | null;
        };
        /** SamplePartialUpdate */
        SamplePartialUpdate: {
            /** Email（照合用・必須） */
            email: string;
            /** Name */
            name?: string | null;
            /**
             * Date
             * Format: date-time
             */
            date?: string | null;
            /** Place */
            place?: string | null;
            trouble_type?: string | null;
            trouble_detail?: string | null;
            expected_actions?: string | null;
            actual_actions?: string | null;
            error_code?: string | null;
            ai_initial_response?: string | null;
        };
        /** SampleAdminUpdate（管理者画面用） */
        SampleAdminUpdate: {
            /** Status */
            status: 'Pending' | 'Temporarily Resolved' | 'Fully Resolved';
            /** Admin Comment */
            admin_comment?: string | null;
        };
        /** SampleMessageCreate */
        SampleMessageCreate: {
            author_role: 'staff' | 'admin';
            body: string;
            email?: string | null;
        };
        /** SampleMessageResponse */
        SampleMessageResponse: {
            id: number;
            sample_id: number;
            author_role: 'staff' | 'admin';
            body: string;
            /** Format: date-time */
            created_at: string;
        };
        // ===== 追加ここまで =====
        /** SampleResponse */
        SampleResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Place */
            place: string;
            trouble_type: string;
            trouble_detail: string;
            expected_actions?: string | null;
            actual_actions?: string | null;
            error_code?: string | null;
            ai_initial_response?: string | null;
            /** Status（管理者対応状況。初期値 Pending） */
            status?: 'Pending' | 'Temporarily Resolved' | 'Fully Resolved';
            /** Admin Comment */
            admin_comment?: string | null;
            /** 一時保存（トップページ） */
            is_draft?: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_samples_samples_get: {
        parameters: {
            query?: {
                /** @description 空白区切りのキーワード。AND条件・部分一致 */
                q?: string | null;
                /** @description 問題タイプ */
                trouble_type?: string | null;
                // ===== 追加: 日付レンジフィルタ =====
                /** @description この日以降（含む） */
                date_from?: string | null;
                /** @description この日以前（含む） */
                date_to?: string | null;
                /** @description true=一時保存のみ, false=本登録のみ */
                is_draft?: boolean | null;
                /** @description 登録時メールで絞り込み */
                email?: string | null;
                // ===== 追加ここまで =====
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleResponse"][];
                };
            };
        };
    };
    create_sample_samples_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    // ===== 追加: PUT 更新 =====
    update_sample_samples__sample_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    // ===== 追加: PATCH 部分更新 =====
    partial_update_sample_samples__sample_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SamplePartialUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    // ===== 追加ここまで =====
    delete_sample_samples__sample_id__delete: {
        parameters: {
            query: {
                /** @description 登録時と同じメールアドレス */
                email: string;
            };
            header?: never;
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sample_messages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleMessageResponse"][];
                };
            };
        };
    };
    create_sample_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleMessageCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleMessageResponse"];
                };
            };
        };
    };
}
